name: First Workflow
on: workflow_dispatch # means that user has to manually start this workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Hello World Again!"
      - name: Print goodbye
        run: echo "Done - bye!"
